language: rust
rust:
  - nightly-2019-03-23 # pin a rust nightly version because clippy is lagging behind
cache: cargo

services:
  - docker

stages:
  - name: test
    # test on PRs, cron, master or tags
    if: type != push OR branch = master OR tag IS present
  - name: build
    if: (type = push AND branch = master) OR tag IS present

jobs:
  include:
    - stage: test
      script: cargo test
    - stage: build
      before_script: docker run -v $PWD:/volume --rm -t clux/muslrust cargo build --release
      script: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin &&
        docker build . -t potatoengineering/rustaroo-api:$TRAVIS_BRANCH &&
        docker push potatoengineering/rustaroo-api